export const useExperiences = () => [
    {
        position: "Senior Software Developer",
        company: "Vocphone",
        workStart: "Nov. 2021",
        workUntil: '<span class="present-work">Present</span>',
        des: "Full Time <b>Senior Software Developer</b> at <a href='https://www.vocphone.com/' target='_blank'>Vocphone</a>. Responsibilities are to design and implement complex business software problems and lease with management and the end customer.",
        url: "https://www.vocphone.com/",
        year: "2021",
        to: "present",
        timeline: [
            {
                date: "Feb. 2023",
                details: "I became a Project Manager (PM)",
            },
            {
                date: "Nov. 2021",
                details: "Started to work as a Senior Software dev.",
            },
        ],
    },
    {
        position: "Web Developer",
        company: "Webinarinc",
        workStart: "Mar. 2021",
        workUntil: "Nov. 2021",
        des: "Full Time <b>Web Developer</b> at Webinarinc. We focus on developing/debugging/fixing websites, using different technologies to satisfy customers.",
        url: "https://webinarinc.com/",
        year: "2021",
        to: 2021,
    },
    {
        present: true,
        position: "Software Developer",
        company: "Utalk",
        workStart: "August 2019",
        workUntil: "April 2021",
        des: "Maintaining Systems and services to lower the rate of system errors or bugs. We manage, maintain and develop front-end and back-end codes/programs. Engaged in different kinds of frameworks and tools like VueJs, AngularJs, Codeigniter, Lumen/Laravel, and Ruby on Rails. For the Database, we manage MySQL and Mongo Database.",
        url: "https://www.facebook.com/utalkphilippines",
        certificate: {
            link: "https://drive.google.com/file/d/1_CBroR0xY8bq9Z6kcS40opEQf_SC5AZ6/view?usp=sharing",
            label: "Show Employment Certificate",
        },
        year: "2019",
        to: 2021,
    },
    {
        isCard: true,
        title: "SQL Course",
        year: "Mar. <br /> 2021",
        certificate: {
            link: "https://www.sololearn.com/Certificate/CT-LKXLDBLV/png",
            label: "SQL Course Certificate",
        },
        des: "Re-learning the basics of SQL for refreshing my knowledge.",
    },
    {
        isCard: true,
        title: "JavaScript: Theoretical and Practical Understanding",
        year: "Mar. <br /> 2021",
        certificate: {
            link: "https://www.sololearn.com/Certificate/CT-LKXLDBLV/png",
            label: "JavaScript Certificate",
        },
        des: "JavaScript focusing in theoretical and practical understanding",
    },
    {
        isCard: true,
        title: "SMART Technopreneurship 101",
        year: "Sept. <br /> 2020",
        certificate: {
            link: "https://github.com/BroJenuel/BroJenuel/raw/master/certificates/SMARTtechno101_Certificate%20of%20Completion.pdf",
            label: "CERTIFICATE of COMPLETION",
        },
        des: "Took Technopreneurship 101",
    },
    {
        isCard: true,
        title: "SMART Android Mobile Apps Development for Beginners",
        year: "Sept. <br /> 2020",
        certificate: {
            link: "https://github.com/BroJenuel/BroJenuel/raw/master/certificates/SMART%20Android%20Mobile%20Apps%20Development%20for%20Beginners_Certificate%20of%20Completion.pdf",
            label: "CERTIFICATE of COMPLETION",
        },
        des: "Took up android mobile app development for beginner course",
    },
    {
        position: "Web Developer",
        company: "Dap-ayan",
        workStart: "Aug. 2018",
        workUntil: "May 2019",
        des: "Participated as an author and a project developer for the Ordering Management System for the restaurant. We used PHP, JavaScript, HTML, CSS, and MySQL to build the web app.",
        url: "https://www.facebook.com/DapayanCafeExtention",
        certificate: {
            link: "https://drive.google.com/file/d/1TYyF6q4L2NdaXbibUry22UWC7YQpmzPN/view?usp=sharing",
            label: "Show Certificate of Participation",
        },
        year: "2018",
        to: 2019,
    },
    {
        position: "Designer and Web Programmer",
        company: "iLearn",
        workStart: "September. 2018",
        workUntil: "Dec. 2018",
        des: "Being a part of a work that focuses on designs, I have been creating designs for simple magazines using Photoshop and Illustrator. Engaged in Video Editing using Adobe Premiere. Engaged in web programming using JavaScript and PHP.",
        url: "http://www.ilearnsda.com",
        certificate: {
            link: "https://drive.google.com/file/d/1NMz6G-fDcArzRm9odSfL_ntx5Hj0qLu_/view?usp=sharing",
            label: "Show Certificate of Completion",
        },
        year: 2018,
        to: 2018,
    },

    {
        position: "Web Developer Student",
        company: "KCP",
        workStart: "Aug. 2016",
        workUntil: "April 2019",
        des: `I have been a Full-time student at <a href='https://kcp.edu.ph' target='_blank'>Kings College of the Philippines</a>. It is the school where I started learning and experienced programming in Web Development.<br><br>King’s College of the Philippines is a mission school under the auspices of the Northern Luzon Presbyterian Church. Its beginnings can be traced to the arrival of a Korean Missionary, Rev. Kwon Young-Soo in the Philippines in 1991.<br><br>For more than a decade, Missionary Kwon laboriously ministered to a great number of people in the various Cordillera provinces namely: Mt. Province, Kalinga, Apayao, Ifugao, Benguet, Isabela, Cagayan, and also Baguio City. Noting the lack of trained clergy, Rev. Kwon established a Bible School named Zoe Logos Temple Ministry in Sabangan, Mt. Province. Eventually, to address the concern of the growing number of unschooled youth in the Cordilleras, and with assistance from a church and individual sponsors – local and overseas, he established Eastern Luzon Colleges in Bambang, Nueva Vizcaya in 2003 and Eastern Luzon Colleges in 2004 in La Trinidad, Benguet.`,
        url: "https://kcp.edu.ph/",
        certificate: {
            link: "https://drive.google.com/file/d/1p7I8t2maRU5vXJYjdE2-Cw1SiJJOVyYd/view?usp=sharing",
            label: "Show Certificate of Fulfillment",
        },
        year: 2016,
        to: 2019,
    },
    {
        isCard: true,
        title: "ENTREPRENEUR SUMMIT BAGUIO 2018",
        year: "Sept. <br /> 2018",
        certificate: {
            link: "https://drive.google.com/file/d/1-YmSIGUmX0QQyBUjCJHBVIjSsr3rwmJj/view",
            label: "Certificate of Attendance",
        },
        des: "Joined the 2nd Entrepreneur Summit Baguio held on september 23, 2018 at the university of Baguio, Upper General Luna Baguio City Benguet, 2600",
    },
    {
        isCard: true,
        title: "PHP Course Certificate",
        year: "March <br /> 2018",
        certificate: {
            link: "https://www.sololearn.com/Certificate/CT-3RLQL1CI/pdf",
            label: "PHP Course Certificate",
        },
        des: "Learned basics of PHP in SoloLearn.",
    },
    {
        isCard: true,
        title: "JavaScript Course Certificate",
        year: "March <br /> 2018",
        certificate: {
            link: "https://www.sololearn.com/Certificate/1024-214029/pdf",
            label: "JavaScript Course Certificate",
        },
        des: "Learned basics of JavaScript in SoloLearn.",
    },
    {
        isCard: true,
        title: "CSS Course Certificate",
        year: "January <br /> 2018",
        certificate: {
            link: "https://www.sololearn.com/Certificate/CT-56OTDVDU/pdf",
            label: "CSS Course Certificate",
        },
        des: "Learned basics of CSS in SoloLearn.",
    },
    {
        isCard: true,
        title: "HTML Course Certificate",
        year: "November <br /> 2017",
        certificate: {
            link: "https://www.sololearn.com/Certificate/CT-TCJJRFMV/pdf",
            label: "HTML Certificate",
        },
        des: "Learned basics of HTML in SoloLearn.",
    },
];
