export const useSkills = () => [
    {
        icon: "icon--solar icon--solar--window-frame-bold-duotone",
        tech: "Front-End Developer",
        description: `I create visual and interactive elements of websites and web applications that users see and interact with.`,
        tools: [
            {
                icon: "icon--skill-icons icon--skill-icons--javascript",
                icon_svg: "skill-icons:javascript",
                text: "JavaScript",
                description: `JavaScript is a lightweight, interpreted, or just-in-time compiled programming language with first-class functions that adds interactivity to your website.`,
                link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
            },
            {
                icon: "icon--logos icon--logos--vue",
                icon_svg: "logos:vue",
                text: "Vue",
                description: `Vue.js is an open-source model–view–viewmodel front end JavaScript framework for building user interfaces and single-page applications. It was created by Evan You, and is maintained by him and the rest of the active core team members. <a href="https://vuejs.org/" target="_blank" alt="Go To VueJS">Go To VueJS</a>`,
                link: "https://vuejs.org/",
            },
            {
                icon: "icon--logos icon--logos--nuxt-icon",
                icon_svg: "logos:nuxt-icon",
                text: "Nuxt JS",
                description: `Build your next Vue.js application with confidence using NuxtJS. An open source framework making web development simple and powerful. <a href="https://nuxtjs.org/" target="_blank" alt="go to Nuxtjs">Go To NuxtJS</a>`,
                link: "https://nuxt.com",
            },
            {
                icon: "icon--logos icon--logos--nodejs-icon",
                icon_svg: "logos:nodejs-icon",
                text: "NodeJs",
                description: `Node.js is an open-source, cross-platform, back-end JavaScript runtime environment that runs on the V8 engine and executes JavaScript code outside a web browser.`,
                link: "https://nodejs.org/en/",
            },
            {
                icon: "icon--logos icon--logos--typescript-icon",
                icon_svg: "logos:typescript-icon",
                text: "TypeScript",
                description: `Its actually like javascript but focuses more on types, this was created to be useful on IDEs like VS Code, and also help lower type errors in the future, specially as the project grows. <a href="https://www.typescriptlang.org/">To Know More Click Here</a>`,
                link: "https://www.typescriptlang.org/",
            },
            {
                icon: "icon--logos icon--logos--tailwindcss-icon",
                icon_svg: "logos:tailwindcss-icon",
                text: "tailwindcss",
                description: `A utility-first CSS framework packed with classes like flex, pt-4, text-center and rotate-90 that can be composed to build any design, directly in your markup.`,
                link: "https://tailwindcss.com/",
            },
            {
                icon: "icon--logos icon--logos--windi-css",
                icon_svg: "logos:windi-css",
                svg: true,
                text: "windicss",
                description: `If you are already familiar with Tailwind CSS, think about Windi CSS as an on-demand alternative to Tailwind, which provides faster load times, fully compatible with Tailwind v2.0 and with a bunch of additional cool features.`,
                link: "https://windicss.org/",
            },
            {
                icon: "icon--logos icon--logos--sass",
                icon_svg: "logos:sass",
                text: "SASS",
                description: `CSS with superpowers. Sass is the most mature, stable, and powerful professional grade CSS extension language in the world.`,
                link: "https://sass-lang.com/",
            },
            {
                icon: "icon--skill-icons icon--skill-icons--html",
                icon_svg: "skill-icons:html",
                text: "html5",
                description: `HTML5 is a markup language used for structuring and presenting content on the World Wide Web. It is the fifth and last major HTML version that is a World Wide Web Consortium recommendation. The current specification is known as the HTML Living Standard.`,
                link: "https://developer.mozilla.org/en-US/docs/Web/HTML",
            },
            {
                icon: "icon--logos icon--logos--figma",
                icon_svg: "logos:figma",
                text: `Figma`,
                description: `As a developer that also works with frontend development, I started to learn and gain experience in UX designing because I want it to be User Friendly. Figma is great for creating designs and is what I use.`,
                link: "https://www.figma.com/",
            },
            {
                icon: "icon--logos icon--logos--bootstrap",
                icon_svg: "logos:bootstrap",
                text: `Bootstrap`,
                description: `Bootstrap is a free and open-source CSS framework directed at responsive, mobile-first front-end web development. It contains HTML, CSS and JavaScript-based design templates for typography, forms, buttons, navigation, and other interface components.`,
                link: "https://getbootstrap.com/",
            },
            {
                icon: "icon--logos icon--logos--unocss",
                icon_svg: "logos:unocss",
                text: `UnoCSS`,
                description: `UnoCSS is the instant atomic CSS engine, that is designed to be flexible and extensible. The core is un-opinionated, and all the CSS utilities are provided via presets.`,
                link: "https://unocss.dev/",
            },
            {
                icon: "icon--skill-icons icon--skill-icons--electron",
                icon_svg: "skill-icons:electron",
                text: "Electron",
                description: `Electron is a JavaScript framework for building cross-platform desktop applications.`,
                link: "https://www.electronjs.org/",
            },
        ],
    },
    {
        icon: "icon--solar icon--solar--server-path-line-duotone",
        tech: "Back-End Developer",
        description: `I develop and maintain the server-side of websites and web applications, managing databases, and ensuring the functionality and data handling of the software`,
        tools: [
            {
                icon: "icon--skill-icons icon--skill-icons--php-dark",
                icon_svg: "skill-icons:php-dark",
                text: "PHP",
                description: `PHP is a widely-used open source general-purpose scripting language that is especially suited for web development and can be embedded into HTML.`,
                link: "https://www.php.net/",
            },
            {
                icon: "icon--logos icon--logos--codeigniter-icon",
                icon_svg: "logos:codeigniter-icon",
                teny: true,
                text: "CodeIgniter",
                description:
                    "CodeIgniter is a powerful PHP framework with a very small footprint, built for developers who need a simple and elegant toolkit to create full-featured web applications.",
                link: "https://codeigniter.com/",
            },
            {
                icon: "icon--logos icon--logos--laravel",
                icon_svg: "logos:laravel",
                teny: true,
                text: "laravel/Lumen",
                description:
                    "<a href='https://laravel.com/' target='_blank' alt='Go to Laravel'>Laravel</a> is a free, open-source PHP web framework, created by Taylor Otwell and intended for the development of web applications following the model–view–controller architectural pattern and based on Symfony. Laravel <a href='https://lumen.laravel.com/' target='_blank' alt='Go to lumen'>Lumen</a> is a stunningly fast PHP micro-framework for building web applications with expressive, elegant syntax.",
                link: "https://laravel.com/",
            },
            {
                icon: "icon--skill-icons icon--skill-icons--mysql-dark",
                icon_svg: "skill-icons:mysql-dark",
                text: `MySQL`,
                description: `MySQL is an open-source relational database management system (RDBMS) that is widely used for managing and organizing structured data. It's one of the most popular choices for powering web applications, content management systems, and various other types of software that require a reliable and efficient way to store and retrieve data.`,
                link: "https://www.mysql.com/",
            },
            {
                icon: "icon--logos icon--logos--postgresql",
                icon_svg: "logos:postgresql",
                text: `PostgreSQL`,
                description: `PostgreSQL is a powerful, open source object-relational database system with over 35 years of active development that has earned it a strong reputation for reliability, feature robustness, and performance.`,
                link: "https://www.postgresql.org/",
            },
            {
                icon: "icon--skill-icons icon--skill-icons--mongodb",
                icon_svg: "skill-icons:mongodb",
                text: `MongoDB`,
                description: `MongoDB is a source-available cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas.`,
                link: "https://www.mongodb.com/",
            },
            {
                icon: "icon--logos icon--logos--firebase",
                icon_svg: "logos:firebase",
                text: `Firebase`,
                description: `Firebase, Inc. is a set of backend cloud computing services and application development platforms provided by Google. It hosts databases, services, authentication, and integration for a variety of applications, including Android, iOS, JavaScript, Node.js, Java, Unity, PHP, and C++.`,
                link: "https://firebase.google.com/",
            },
            {
                icon: "icon--skill-icons icon--skill-icons--supabase-light",
                icon_svg: "skill-icons:supabase-light",
                text: `SupaBase`,
                description: `Supabase is an open source Firebase alternative.
                Start your project with a Postgres database, Authentication, instant APIs, Edge Functions, Realtime subscriptions, Storage, and Vector embeddings.`,
                link: "https://supabase.com/",
            },
            {
                icon: "icon--skill-icons icon--skill-icons--vercel-dark",
                icon_svg: "skill-icons:vercel-dark",
                text: `Vercel`,
                description: `Vercel is a platform for building, deploying, and scaling next-generation applications.`,
                link: "https://vercel.com/",
            },
        ],
    },
    {
        icon: "icon--solar icon--solar--settings-minimalistic-bold",
        tech: "Technologies",
        description: "I am also familiar with the following tools for development.",
        tools: [
            {
                icon: "icon--devicon icon--devicon--git",
                icon_svg: "devicon:git",
                text: "Git",
                description: `Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency.`,
                link: "https://git-scm.com/",
            },
            {
                icon: "icon--devicon icon--devicon--vscode",
                icon_svg: "devicon:vscode",
                text: "VS Code",
                description: `VS Code is a source-code editor that is built specifically for building and debugging modern web and cloud applications.`,
                link: "https://code.visualstudio.com/",
            },
            {
                icon: "icon--simple-icons icon--simple-icons--laragon",
                icon_svg: "simple-icons:laragon",
                text: "Laragon",
                description: `Laragon is a free and open-source cross-platform desktop application development environment for Windows, macOS, and Linux.`,
                link: "https://www.laragon.org/",
            },
            {
                icon: "icon--logos icon--logos--phpstorm",
                icon_svg: "logos:phpstorm",
                text: "PhpStorm",
                description: `PhpStorm is a free, open-source, cross-platform IDE for web and desktop applications developed by JetBrains.`,
                link: "https://www.jetbrains.com/phpstorm/",
            },
            {
                icon: "icon--logos icon--logos--webstorm",
                icon_svg: "logos:webstorm",
                text: "WebStorm",
                description: `WebStorm is a free, open-source, cross-platform IDE for web and desktop applications developed by JetBrains.`,
                link: "https://www.jetbrains.com/webstorm/",
            },
        ],
    },
];
